return PlaceObj('ModDef', {
	'title', "MMGGA - Make Machine Guns Great Again",
	'description', "Patch 1.03 has ruined Machine Guns. This mod tries to make them great again, but preserve balance. Compatible with JA3 v1.5.1.\nFeatures:\n- MG Interrupt count is not limited by AP but ammo in the magazine\n- Smaller MG magazines, more AP to reload\n- Break MG OW by Suppressing, Burning, or dealing Explosive damage\n- Adjustable OW range\n- MG benefit from MRK, STR, and HLT. Less dependency on AGI/DEX.",
	'image', "Mod/FGAVv33/img/MMGGA_Logo512.png",
	'last_changes', '- Compatible with JA3 v1.5.1\n- An option to control NEXT TURN AP\n- An option to adjust MG Minimum Interrupt Attacks\n- An option to unlock short MG OW ranges\n- Fixed "Pack MG" AP cost for Heavy Weapons perk',
	'dependencies', {},
	'id', "FGAVv33",
	'author', "[ScrN]PooSH",
	'version_major', 1,
	'version_minor', 2,
	'version', 253,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/mmgga.lua",
	},
	'default_options', {
		mmgga_APDeposit = true,
		mmgga_MGFreeInterruptAttacks = "3 (Default)",
		mmgga_ShortOW = false,
	},
	'has_data', true,
	'saved', 1759427692,
	'code_hash', -7941042612715971234,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "GameRuleDef",
			'Id', "mmgga_rules",
			'ClassDisplayName', "Game rule",
		}),
	},
	'steam_id', "3018879222",
	'TagBalancing&Difficulty', true,
	'TagCombat&AI', true,
	'TagWeapons&Items', true,
})