return PlaceObj('ModDef', {
	'title', "MMGGA - Make Machine Guns Great Again",
	'description', "Patch 1.03 has ruined Machine Guns. This mod tries to make them great again, but preserve balance. Compatible with 1.1.0.\nFeatures:\n- MG Interrupt count is not limited by AP but ammo in the magazine\n- Smaller MG magazines, more AP to reload\n- Break MG OW by Suppressing, Burning, or dealing Explosive damage\n- Adjustable OW range\n- MG benefit from MRK, STR, and HLT. Less dependency on AGI/DEX.",
	'image', "Mod/FGAVv33/img/MMGGA_Logo512.png",
	'last_changes', '- An option to control NEXT TURN AP\n- An option to adjust MG Minimum Interrupt Attacks\n- An option to unlock short MG OW ranges\n- Fixed "Pack MG" AP cost for Heavy Weapons perk',
	'dependencies', {},
	'id', "FGAVv33",
	'author', "[ScrN]PooSH",
	'version_major', 1,
	'version_minor', 1,
	'version', 248,
	'lua_revision', 233360,
	'saved_with_revision', 340147,
	'code', {
		"Code/mmgga.lua",
	},
	'has_options', true,
	'saved', 1692721372,
	'code_hash', 5503856055412556824,
	'steam_id', "3018879222",
})